version: '3.8'

services:
  app:
    image: lmsfelipe/surfcheckerapi:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - '9080:9080'
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - EVOLUTION_API_URL=${EVOLUTION_API_URL}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - EVOLUTION_INSTANCE_NAME=${EVOLUTION_INSTANCE_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - ZeekyNet
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.surfchecker.rule=Host(`surfchecker.zeeky.com.br`)'
      - 'traefik.http.routers.surfchecker.tls.certresolver=letsencryptresolver'
      - 'traefik.http.routers.surfchecker.service=surfchecker'
      - 'traefik.http.routers.surfchecker.entrypoints=websecure'
      - 'traefik.http.routers.surfchecker.priority=1'
      - 'traefik.http.services.surfchecker.loadbalancer.server.port=9080'
      - 'traefik.http.services.surfchecker.loadbalancer.passHostHeader=true'
      - 'traefik.docker.network=ZeekyNet'
networks:
  ZeekyNet:
    external: true
    attachable: true
    name: ZeekyNet
