FROM node:24.4-bullseye-slim

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# Don't copy node_modules and dist
COPY . .

EXPOSE 9080

# Use nodemon for development
CMD ["npm", "run", "dev"]