version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: surfchecker-api
    volumes:
      - ./src:/app/src
      - ./.wwebjs_auth:/app/.wwebjs_auth
    ports:
      - '9000:9080'
    environment:
      - MONGO_URI=mongodb://mongo:27017/surfchecker
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
