const waitingMessages = [
  'No embalo dessa onda de informações 🌊, saca só: o surfe nasceu no Havaí há mais de 500 anos.',
  'Remando na maré dos dados, já ouviu falar que o maior tubo já surfado tinha mais de 20 metros de altura? 🏄',
  'Pegando a crista dessa resposta, adivinha só: Kelly Slater já ganhou 11 títulos mundiais 🏆.',
  'No set perfeito de informações 🌊, manda essa pro repertório: a maior onda já registrada foi em Nazaré, Portugal.',
  'Ajustando o leash das ideias, você já percebeu que ele só foi inventado nos anos 70? 🔗',
  'No line-up das respostas, já ficou sabendo que Pipeline é considerada a onda mais perigosa do mundo? 🌊',
  'Deslizando nessa parede de dados 🏄, olha essa: as pranchas já foram feitas de madeira maciça.',
  'Sentindo a brisa das informações 💨, anota aí: o vento offshore deixa a onda mais perfeita.',
  'No tubo dessa resposta, sabia que o Brasil já teve 4 campeões mundiais de surfe? 🇧🇷',
  "Surfando na marola dos fatos, já reparou que tubos são chamados de 'barrels' em inglês?",
  'Checando a previsão dessa resposta 📅, pega essa: a lua cheia influencia no tamanho das ondas.',
  "Pegando a corrente certa de informação, você sabia que 'rip current' é a corrente que te puxa pro fundo? ⚠️",
  "Chegando na crista da resposta, olha só que maneiro: a 'crista' é o ponto mais alto da onda.",
  "Na série de respostas que tá entrando, já ouviu que 'line-up' é onde os surfistas aguardam as ondas?",
  "Remando na maré certa de dados, anota essa curiosidade: existe surfe em rios, chamado 'river surfing' 🏞️.",
  'No swell dessas informações 🌊, já ouviu falar que Duke Kahanamoku é considerado o pai do surfe moderno?',
  "No drop dessa resposta, olha só: o 'bottom turn' é uma das manobras mais importantes do surfe.",
  'Nessa onda de conhecimento 📚, já sabia que a prancha mais longa do mundo tinha mais de 12 metros?',
  'No set que tá chegando, anota aí: o surfe é esporte olímpico desde Tóquio 2020 🥇.',
  'Remando com força nos dados 💪, você já viu que existem ondas artificiais perfeitas em piscinas de surfe?',
  "Na parede dessa informação 🌊, olha essa: Teahupo'o, no Taiti, é famosa pelas ondas pesadas e perigosas.",
  'Sentindo a vibe dessa maré ✨, sabia que o surfe já foi proibido no Havaí no século 19?',
  "No pico dessas respostas, manda essa: 'Hang ten' é quando o surfista coloca os dez dedos dos pés no bico da prancha 🦶.",
  'Remando contra a corrente de dados, sabia que a prancha de surfe já teve quilha removível apenas nos anos 30?',
  'Pegando a direita dessa informação, já ouviu falar que a praia de Bells Beach, na Austrália 🇦🇺, é um ícone do surfe?',
  'Na esquerda dessa resposta, olha só: a prancha mais leve do mundo pesa menos de 2 kg.',
  "Dropando essa onda de dados 🏄, você já reparou que 'longboard' e 'shortboard' são estilos totalmente diferentes?",
  'No pico da informação, sabia que surfistas treinam equilíbrio em pranchas de equilíbrio em terra firme?',
  'Surfando no swell dos fatos 🌊, olha essa: existem competições de surfe noturno com iluminação especial.',
  "Remando nessa maré de curiosidades, já sabia que o Brasil é chamado de 'Brazilian Storm' no surfe mundial? 🇧🇷",
  'No inside dessa resposta, anota aí: surfistas usam parafina pra evitar escorregar na prancha 🕯️.',
  'Chegando no outside das ideias, sabia que ondas tubulares são mais comuns em recifes? 🪸',
  'No fundo dessa corrente de dados, já ouviu falar que surfistas profissionais viajam o mundo inteiro atrás do swell perfeito? ✈️',
  "Seguindo a correnteza das informações, sabia que 'wipeout' é quando o surfista leva um tombo na onda? 💦",
  'Na calmaria entre séries, olha essa: o maior campeonato de surfe do mundo é o WSL Championship Tour 🏆.',
  'No line-up das ideias, manda essa: a Indonésia 🇮🇩 é um dos destinos mais procurados por surfistas.',
  'No swell das respostas, sabia que existem pranchas com propulsão elétrica? ⚡',
  'Na remada dessas informações, você já viu que existem mais de 20 tipos de manobras no surfe?',
  'No drop dessa série, olha só: surfistas usam joelheiras e capacetes em ondas muito pesadas 🪖.',
  "No tubo das curiosidades, já sabia que existem ondas que quebram no mesmo lugar todos os anos, chamadas 'point breaks'?",
  'Seguindo essa maré de dados 🌊, manda essa: a primeira competição oficial de surfe foi em 1928 na Califórnia 🇺🇸.',
  'Nessa onda de respostas, sabia que o surfe adaptado é uma modalidade para pessoas com deficiência? ♿',
  'Na vibe dessa informação, olha essa: existem museus dedicados exclusivamente ao surfe 🏛️.',
  'No swell perfeito de ideias, já ouviu falar que surfistas experientes conseguem prever ondas pelo vento e maré?',
  'No balanço dessa maré 🌊, sabia que as quilhas mudaram radicalmente o surfe nos anos 30?',
  'Dropando essa resposta, olha só: surfistas usam leash para evitar perder a prancha 🔗.',
  'No set dessas informações, você já reparou que as ondas têm nomes diferentes de acordo com o pico?',
  'No embalo dessa maré, sabia que o surfe foi adicionado aos X Games em 2003? 🎮',
  "No bico dessa resposta 🏄, olha essa: 'Noseriding' é quando o surfista fica no bico da prancha por vários segundos.",
  'Na crista dessa onda de dados 🌊, sabia que o surfe em ondas gigantes exige treino de apneia? 🫁',
  'Remando nessa vibe de informações, já ouviu falar que existe campeonato de surfe em ondas de lago?',
  'No swell dessa resposta, olha essa: Mavericks, na Califórnia 🇺🇸, é famosa por ondas gigantes e frias.',
  'Na corrente dessa ideia, sabia que algumas ondas chegam a mais de 80 km/h? 💨',
  'No embalo das marés, manda essa: surfistas usam diferentes tipos de quilha para manobras específicas.',
  "Na parede dessa informação 🌊, sabia que 'Goofy foot' é quando o surfista surfa com o pé direito à frente?",
  "Dropando nessa resposta 🏄, olha só: 'Regular foot' é quando o pé esquerdo fica à frente na prancha.",
  'No set dessas curiosidades, já reparou que algumas praias têm ondas só em determinadas estações do ano?',
  'Remando nesse swell de informações, sabia que o recorde de maior onda surfada é de 26,21 metros? 🌊',
  'No inside dessa curiosidade, olha essa: existem pranchas feitas de garrafas PET recicladas ♻️.',
  'Na vibe dessa resposta, sabia que o surfe também pode ser feito em gelo 🧊, em regiões polares?',
  'Seguindo a corrente dessa informação, já ouviu falar que surfistas profissionais têm fisioterapeutas dedicados?',
  "No balanço dessa onda de dados 🏄, olha essa: o 'cutback' é uma manobra para voltar à parte mais potente da onda.",
  'Na crista dessa curiosidade 🌊, sabia que existe campeonato de surfe só para pranchas retrô?',
  "No drop dessa ideia, olha só: o 'aerial' é uma manobra em que o surfista salta fora da onda.",
  'No set dessas respostas, já ouviu falar que o Havaí 🇺🇸 tem leis que protegem spots tradicionais de surfe?',
  'Na maré dessas informações, sabia que surfistas usam drones para analisar ondas? 🚁',
  "No swell dessa ideia 🌊, olha essa: 'Duck dive' é a técnica para passar por baixo das ondas remando.",
  'Na parede dessa onda de dados, sabia que o Brasil já sediou etapas da WSL em Saquarema? 🇧🇷',
  'No embalo dessas curiosidades, já reparou que cada praia tem sua própria cultura de surfe?',
  'No bico dessa maré de ideias 🏄, olha essa: existem pranchas dobráveis para facilitar o transporte.',
  'Na crista dessa informação 🌊, sabia que existem ondas que quebram a mais de 1 km da costa?',
  'No swell dessa resposta, já ouviu falar que a Austrália 🇦🇺 tem mais de 2.000 praias para surfe?',
  'Na vibe dessas informações, olha essa: surfistas treinam força em piscinas de correnteza 💪.',
  "No drop dessas ideias 🏄, sabia que 'floater' é uma manobra onde o surfista desliza pelo topo da onda?",
  "No set dessa curiosidade, já reparou que o surfe de ondas gigantes é praticado com pranchas especiais chamadas 'gun'?",
  'Na corrente dessa maré 🌊, sabia que alguns surfistas usam capacete até em ondas pequenas para segurança?',
  'No inside dessa informação, olha essa: o surfe é muito popular também na África do Sul 🇿🇦.',
  'No embalo desse swell, sabia que existem ondas perfeitas geradas por barcos? 🚤',
  'Na crista dessa marola, já ouviu falar que algumas ondas quebram apenas durante a maré baixa?',
  'Na vibe dessa resposta ✨, olha essa: existem pranchas feitas de bambu laminado.',
  'No swell dessa maré de dados 🌊, sabia que a Polinésia Francesa é um dos berços do surfe?',
  'No pico dessa curiosidade, já reparou que muitos surfistas também praticam skate 🛹 para treinar manobras?',
  'No set dessa maré, olha essa: surfistas usam aplicativos 📱 para monitorar swell e vento.',
  'Na parede dessa ideia 🌊, sabia que ondas com fundo de coral podem ser mais perigosas? 🪸',
  'No drop dessa resposta 🏄, já ouviu falar que alguns surfistas viajam com mais de 10 pranchas?',
  'No swell dessa informação 🌊, olha essa: ondas com fundo de areia são mais seguras para iniciantes.',
  'Na crista dessa série, sabia que a água fria ajuda na formação de ondas perfeitas? ❄️',
  'Na vibe dessa maré de dados, já reparou que o surfe é praticado até em locais sem mar, com simuladores?',
  'No pico dessa resposta 🏄, olha essa: surfistas experientes sabem a direção do swell só de olhar pro horizonte.',
  'Na corrente dessa onda 🌊, sabia que o surfe também é usado em terapias para reabilitação? ❤️',
  'No embalo dessa informação, já ouviu falar que o surfe tem sua própria linguagem e gírias únicas?',
  'No swell dessa curiosidade 🌊, olha essa: o recorde de mais surfistas numa mesma onda é de 511 pessoas.',
  'Na crista dessa ideia, sabia que surfistas podem gastar anos treinando para uma única onda perfeita?',
  'No bico dessa série 🏄, já reparou que as pranchas modernas usam resina ecológica em alguns modelos?',
  "Na vibe dessa curiosidade ✨, olha essa: 'Layback' é uma manobra onde o surfista encosta as costas na onda.",
  'No set dessa maré de dados 🌊, sabia que ondas geradas por tempestades podem viajar milhares de quilômetros?',
  'Na corrente dessa informação, já ouviu falar que surfistas antigos passavam meses esculpindo uma prancha?',
  'No swell dessa série 🌊, olha essa: a prancha mais cara do mundo foi vendida por mais de 1 milhão de dólares 💰.',
  'No pico dessa onda de informações 🏄, sabia que alguns surfistas usam GPS na prancha para registrar trajetos?',
  'No drop dessa curiosidade, já reparou que existem escolas de surfe até em desertos com ondas artificiais?',
];

export const randomWaitingMessage = () =>
  waitingMessages[Math.floor(Math.random() * waitingMessages.length)];
