- name: SSH & Deploy
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    script: |
      cd /apps/surfchecker-bot
      git pull origin main

- name: Trigger Portainer Redeploy
  run: |
    curl -X POST "${{ secrets.PORTAINER_URL }}/api/stacks/${{ secrets.STACK_ID }}/git/redeploy" \
      -H "Authorization: Bearer ${{ secrets.PORTAINER_TOKEN }}"
